# Generated by Django 2.2.24 on 2023-04-25 07:16

from django.db import migrations
import phonenumbers


def add_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_possible_number(phone) and phonenumbers.is_valid_number(phone):
            flat.owner_pure_phone = phonenumbers.format_number(phone, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230425_1014'),
    ]

    operations = [
        migrations.RunPython(add_pure_phone),
    ]
