# Generated by Django 2.2.24 on 2023-04-25 07:59

from django.db import migrations
import phonenumbers


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, is_created = Owner.objects.get_or_create(
            name=flat.owner,
            pure_phone=flat.owner_pure_phone,
            phonenumber=flat.owners_phonenumber,
        )
        owner.flats.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners),
    ]
